import type { ImageSource } from "./types";

export type AwardItem = {
  id: string;
  year: string;
  projectName: string;
  projectCategoryColor?: string;
  awardTitle: string;
  commendation?: string;
  image: ImageSource;
};

export const DUMMY_AWARDS: AwardItem[] = [
  {
    id: "aw-1",
    year: "2022",
    projectName: "NBRS Miscellaneous",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "AIA Best in Practice Award",
    image: "/images/about/practice1.jpg",
  },
  {
    id: "aw-2",
    year: "2024",
    projectName: "The Pavilion Performing Arts Centre",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2024 AIA Chapter Architecture Awards- NSW Architecture Awards",
    commendation: "Commendation for Sustainable Architecture",
    image: "/images/home/sector2.png",
  },
  {
    id: "aw-3",
    year: "2024",
    projectName: "The Pavilion Performing Arts Centre",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2024 AIA Chapter Architecture Awards- NSW Architecture Awards",
    commendation: "Commendation for Public Architecture",
    image: "/images/home/sector2.png",
  },
  {
    id: "aw-4",
    year: "2024",
    projectName: "Porter House",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2024 The Greenway Award",
    image: "/images/home/sector3.png",
  },
  {
    id: "aw-5",
    year: "2023",
    projectName: "Waves Fitness and Aquatic Centre",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2023 National Awards for Local Government",
    commendation: "Cohesive Communities Category",
    image: "/images/home/sector5.png",
  },
  {
    id: "aw-6",
    year: "2023",
    projectName: "Bay Pavilions Arts + Aquatics",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2023 Australian Institute of Architects NSW",
    commendation: "Sustainable Architecture",
    image: "/images/home/sector1.png",
  },
  {
    id: "aw-7",
    year: "2022",
    projectName: "Bay Pavilions Arts + Aquatics",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2022 Australian Sport, Recreation and Play Innovation Awards",
    commendation: "Sport and Leisure Facility Design",
    image: "/images/home/sector1.png",
  },
  {
    id: "aw-8",
    year: "2021",
    projectName: "Armidale",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2021 Learning Environments Australasia NSW Chapter",
    commendation: "New Construction/New Educational Facility Winner",
    image: "/images/hero/hero1.png",
  },
  {
    id: "aw-9",
    year: "2021",
    projectName: "Dillwynia Correctional Centre Expansion",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2021 American Institute of Architects Justice Facilities Award",
    image: "/images/home/sector4.png",
  },
  {
    id: "aw-10",
    year: "2020",
    projectName: "Cairnsfoot School for Additional Needs",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2020 Australian Institute of Landscape Architecture Awards",
    commendation: "Education and Health Landscape",
    image: "/images/hero/hero2.png",
  },
  {
    id: "aw-11",
    year: "2019",
    projectName: "Taronga Institute of Science and Learning",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2023 National Biophilic Design Awards -Building Scale",
    image: "/images/hero/hero3.png",
  },
  {
    id: "aw-12",
    year: "2019",
    projectName: "Taronga Institute of Science and Learning",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2019 Australian Institute of Architects NSW Architecture Awards",
    commendation: "NSW Educational Architecture Award",
    image: "/images/hero/hero3.png",
  },
  {
    id: "aw-13",
    year: "2019",
    projectName: "Taronga Institute of Science and Learning",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2019 Learning Environments Australasia",
    commendation: "Excellence in Education Facility Design",
    image: "/images/hero/hero3.png",
  },
  {
    id: "aw-14",
    year: "2019",
    projectName: "Fairfield Public School",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2019 Victorian School Building Authority Awards",
    commendation: "Best Primary School",
    image: "/images/hero/hero4.png",
  },
  {
    id: "aw-15",
    year: "2012",
    projectName: "Willoughby Uniting Church",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "2012 Willoughby Council Awards",
    commendation: "Heritage Award",
    image: "/images/hero/hero5.png",
  },
  {
    id: "aw-16",
    year: "1984",
    projectName: "Parklea Prison",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "1984 AIA NSW Sir John Sulman Award for a Building of Outstanding Merit",
    image: "/images/hero/hero6.png",
  },
  {
    id: "aw-17",
    year: "1979",
    projectName: "St Andrew's House",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "1979 AIA NSW Merit Award for an Outstanding Building",
    image: "/images/home/sector2.png",
  },
  {
    id: "aw-18",
    year: "1978",
    projectName: "St Andrew's House",
    projectCategoryColor: "#F0C7BD",
    awardTitle: "1978 AIA NSW Merit Award for a Work of Outstanding Environmental Design",
    image: "/images/home/sector3.png",
  },
];
